//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WsAgendaReuniao
{
    using System;
    using System.Collections.Generic;
    
    public partial class Periodos
    {
        public int IdPeriodo { get; set; }
        public string NomePeriodo { get; set; }
    }
}
