//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WsAgendaReuniao
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservas
    {
        public int IdReserva { get; set; }
        public Nullable<System.DateTime> DtDaReserva { get; set; }
        public Nullable<System.DateTime> DtReservada { get; set; }
        public Nullable<int> IdFuncionario { get; set; }
        public Nullable<int> IdSala { get; set; }
        public Nullable<int> IdPeriodo { get; set; }
        public string Funcionario { get; set; }
        public string Sala { get; set; }
        public string Periodo { get; set; }
    }
}
